#!/bin/sh
#open $BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME

ditto $PROJECT_DIR/../Lottery/images/selected/ $BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME/${EXECUTABLE_NAME}.app/
ditto $PROJECT_DIR/../Lottery/images/unselected/ $BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME/${EXECUTABLE_NAME}.app/
ditto $PROJECT_DIR/../Lottery/images/icon/ $BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME/${EXECUTABLE_NAME}.app/

